eBillingSuite/sourcecode/eBillingSuite.Host/Controllers/SupportController.cs
using eBillingSuite.Globalization;
using eBillingSuite.Model.EBC_DB;
using eBillingSuite.Repositories.Support;
using eBillingSuite.ViewModels;
using MvcFlash.Core;
using MvcFlash.Core.Extensions;
using Shortcut.PixelAdmin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace eBillingSuite.Controllers
{
    public class SupportController : Controller
    {

        private IPixelAdminPageContext _pixelAdminPageContext;
        private IECCListRepositories _eCConfigRepositories;
        private IeBillingSuiteRequestContext _context;
        private ITicketsRepository _ticketsRepository;



        public SupportController(IPixelAdminPageContext pixelAdminPageContext,
            IECCListRepositories eCConfigRepositories,
            IeBillingSuiteRequestContext context,
            ITicketsRepository ticketsRepository)
        {
            _pixelAdminPageContext = pixelAdminPageContext;
            _eCConfigRepositories = eCConfigRepositories;
            _context = context;
            _ticketsRepository = ticketsRepository;
        }

        // GET: Support
        public ActionResult Index()
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);

            //if (Request.IsAjaxRequest())
            //    return Json(this.PanelContentReply(View()), JsonRequestBehavior.AllowGet);
            //else
            //    return View();

            return View();
        }

        public ActionResult RequestAcessControl()
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);
            var modelVM = new SupportChatVM("","","");
            return PartialView("RequestAcessControl", modelVM);

            
        }

        public ActionResult RemoteAcessRequest(string email, string descricao)
        {
            try
            {
                using (var dbContextTransaction = _ticketsRepository.Context.Database.BeginTransaction())
                {
                    var newTicket = new Tickets
                    {
                        pkid = Guid.NewGuid(),
                        TipoPedido = "RemoteAcess",
                        Descricao = descricao,
                        Email = email,
                        Data = DateTime.Now,
                        Tratado = false,
                    };

                    _ticketsRepository.Set.Add(newTicket);
                    _ticketsRepository.Save();
                    dbContextTransaction.Commit();

                    try
                    {
                        MailMessage e_mail = new MailMessage();
                        e_mail.To.Add("tiago.esteves@pi-co.com");
                        e_mail.Subject = "NOMEDAEMPRESA || Pedido de Acesso Remoto "+DateTime.Now;
                        e_mail.From = new MailAddress(email);
                        e_mail.IsBodyHtml = true;
                        e_mail.Body = "<p>Descrição do Problema: "+descricao+"</p>";
                        e_mail.Priority = MailPriority.High;
                        SmtpClient smtp = new SmtpClient("mail.pi-co.com");
                        smtp.Port = 25;
                        //SmtpClient smtp = new SmtpClient("mail.pi-co.com", 25);
                        smtp.EnableSsl = false;
                        System.Net.NetworkCredential cred = new System.Net.NetworkCredential("ebc.teste@pi-co.com", "eBC#123-PI");
                        smtp.Credentials = cred;
                        smtp.UseDefaultCredentials = true;

                        smtp.Send(e_mail);

                    }
                    catch (Exception e)
                    {
                        //a ver com o tiago
                    }

                    return Json(Flash.Instance.Success("Amazing"));
                    //return true;
                }
            }
            catch(Exception ex)
            {
                return Json(Flash.Instance.Warning("Deste erro!"));
            }

            
        }
    }
}

eBillingSuite/sourcecode/eBillingSuite.Host/Views/Support/Index.cshtml
@{
    var user = User.Identity as eBillingSuite.Security.IeBillingSuiteIdentity;

<div id="content-wrapper">
    <form method="post">
        <div class="panel-heading">
            @*<span class="panel-title"><i class="panel-title-icon fa fa-calendar"></i>@this.Get(DictionaryEntryKeys.TitleForTicketRequest)</span>*@
            <span class="panel-title"><i class="panel-title-icon fa fa-envelope"></i>Diga-nos qual o seu problema:</span>
        </div> <!-- / .panel-heading -->
        <p></p>
        <div class="panel-body">
            <div ng-controller="AppCtrl" ng-app="MyApp">
                @*<select ng-model="selectOption" ng-options="x for x in options"></select>*@
                <select>
                        <option value="Manutencao">Manutenção</option>
                        <option value="ReportBug">Reportar Bug</option>
                        <option value="UpdateSystem">Atualizar o Sistema</option>
                </select>
                <p>&nbsp;</p>
                <p>Para a solução do problema ser mais eficaz, queira nos deixar uma breve descrição</p>
                <textarea class="note-codable"></textarea>
                <div class="panel-footer text-right">
                    <button class="btn btn-primary">@Texts.Submit</button>
                </div>
            </div>
        </div>
    </form>

    @*<p>Se preferir pode contactar-nos para o telefone: 221234567</p>

    <p>Clique aqui para conversar connosco em tempo real:</p>
    <button>CHAT</button>*@
</div> <!-- / #content-wrapper -->
<div id="main-menu-bg"></div>

@*<script>
    var app = angular.module('myApp', []);
    app.controller('AppCtrl', function ($scope) {
        $scope.options = ["Manutencao", "ReportBug", "UpdateSystem"];
    });
</script>*@

eBillingSuite/sourcecode/eBillingSuite.Host/Views/Support/RequestAcessControl.cshtml
@model eBillingSuite.ViewModels.SupportChatVM
@{
    var pc = ViewBag.PixelAdminPageContext as IPixelAdminPageContext;
}

<script>
    $('#submitBtt').on('click', function () {
        location.href = "https://get.teamviewer.com/pi_nosinovamos";
    });
</script>


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Pedido de Acesso Remoto</h4>
</div>
<div class="modal-body">
    <form id="doc-edit-form"
          action="@Url.Action("RemoteAcessRequest", "Support")"
          method="post"
          class="form-horizontal">
        <div class="tab-content">
            <div class="row">
                @Html.PixelAdminTextBoxWithColFor(e => e.Email, 6, null, InputOptions.Default)
            </div>
            <div class="row">
                @*@Html.PixelAdminTextBoxWithColFor("Empresa", 6, null, InputOptions.Default)*@
                @Html.PixelAdminTextBoxWithColFor(e => e.Descricao, 12, null, InputOptions.Default)
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button id="submitBtt" type="button" class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@Texts.Submit</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">@Texts.Close</button>
</div>