eBillingSuite/sourcecode/eBillingSuite.Host/Controllers/StatsController.cs
using eBillingSuite.Model.EBC_DB;
using eBillingSuite.Model.HelpingClasses;
using eBillingSuite.Models;
using eBillingSuite.Repositories;
using eBillingSuite.Repositories.Interfaces;
using eBillingSuite.ViewModels;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Shortcut.PixelAdmin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBillingSuite.Controllers
{
    public class StatsController : Controller
    {
        private IPixelAdminPageContext _pixelAdminPageContext;
        private IEBC_PackageRepository _ebc_packageRepository;
        private IECCListRepositories _eCConfigRepositories;
        private IOutboundInboundRepository _outboundInboundRepository;
        private IComATPacketsRepository _comATPacketRepository;
        private IComATPacketsGuiasRepository _comATPacketGuiasRepository;
        private IeBillingSuiteRequestContext _context;
        private IDocsErrorsRepository docsErrorsRepository;
        private List<InboundPackets> lIP;
        private List<OutboundPackets> lOP;



        public StatsController(IPixelAdminPageContext pixelAdminPageContext,
            IECCListRepositories eCConfigRepositories,
            IeBillingSuiteRequestContext context,
            IOutboundInboundRepository outboundInboundRepository,
            IDocsErrorsRepository docsErrorsRepository,
            IComATPacketsRepository comATPacketRepository,
            IEBC_PackageRepository ebc_packageRepository)
        {
            _pixelAdminPageContext = pixelAdminPageContext;
            _eCConfigRepositories = eCConfigRepositories;
            _context = context;
            _outboundInboundRepository = outboundInboundRepository;
            _comATPacketRepository = comATPacketRepository;
            _ebc_packageRepository = ebc_packageRepository;
        }

        // GET: Stats
        public ActionResult Index(JQueryDataTableParamModel param)
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);

            if (!Request.IsAjaxRequest())
            {
                var modelVM = new EBCStats(_eCConfigRepositories, _context.UserIdentity.Instances);


                return View(modelVM);
            }

            var data = _eCConfigRepositories.outboundInboundRepository.GetAllPackets(_context.UserIdentity).ToList();

            var r = data.Select(o => new
            {
                Sentido = o.Sentido,
                NomeEmiss = o.NomeEmiss,
                NifEmissor = o.NifEmiss,
                NomeReceptor = o.NomeRecept,
                NifReceptor = o.NifRecept,
                NumDoc = o.NumDoc,
                Quantia = o.Quantia,
                DataFatura = String.Join("-", o.Ano, o.Mes, o.Dia),
                DataCriacao = o.DataCriacao,
                TipoDoc = o.TipoDoc,
                Estado = o.Estado,
                Id = o.ID
            });

            if (param.iDisplayLength != 0)
            {
                var recordCount = r.Count();
                var records = r
                    .Skip(param.iDisplayStart)
                    .Take(param.iDisplayLength)
                    .ToList();

                var reply = new JsonNetResult();
                reply.Data = new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = recordCount,
                    iTotalDisplayRecords = param.iDisplayLength,
                    aaData = records
                };

                return reply;
            }
            else
            {
                var records = r.Take(10).ToList();
                var reply = new JsonNetResult();
                reply.Data = new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = r.Count(),
                    iTotalDisplayRecords = records.Count,
                    aaData = r
                };

                return reply;
            }
        }

        public ActionResult GetData(JQueryDataTableParamModel param)
        {
            // Initialization.   
            JsonResult result = new JsonResult();
            try
            {
                var dataFromDB = _eCConfigRepositories.outboundInboundRepository.GetAllPackets(_context.UserIdentity).ToList();

                var data = dataFromDB.Select(o => new OutInPresentation
                {
                    Sentido = o.Sentido,
                    NomeEmissor = o.NomeEmiss,
                    NifEmissor = o.NifEmiss,
                    NomeReceptor = o.NomeRecept,
                    NifReceptor = o.NifRecept,
                    NumDoc = o.NumDoc,
                    Quantia = o.Quantia.ToString(),
                    DataFatura = String.Join("-", o.Ano, o.Mes, o.Dia),
                    DataCriacao = o.DataCriacao,
                    TipoDoc = o.TipoDoc,
                    Estado = o.Estado,
                    Id = o.ID
                }).ToList();


                // Initialization.   
                var searchParam = new SearchParameters
                {
                    estado = Request.Form.GetValues("columns[11][search][value]")[0],
                    numDoc = Request.Form.GetValues("columns[6][search][value]")[0],
                    nifRec = Request.Form.GetValues("columns[5][search][value]")[0],
                    nifEmi = Request.Form.GetValues("columns[3][search][value]")[0],
                    dataFinal = Request.Form.GetValues("columns[2][search][value]")[0],
                    dataInicial = Request.Form.GetValues("columns[1][search][value]")[0]
                };

                string search = Request.Form.GetValues("search[value]")[0];
                string draw = Request.Form.GetValues("draw")[0];
                string order = Request.Form.GetValues("order[0][column]")[0];
                string orderDir = Request.Form.GetValues("order[0][dir]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);
                // Loading.   
                // Total record count.   
                int totalRecords = data.Count;
                // Verification.   
                if (!string.IsNullOrEmpty(search) && !string.IsNullOrWhiteSpace(search))
                {
                    // Apply search   
                    data = data.Where(p => p.Sentido.ToString().ToLower().Contains(search.ToLower()) ||
                        p.NomeEmissor.ToLower().Contains(search.ToLower()) ||
                        p.NifEmissor.ToString().ToLower().Contains(search.ToLower()) ||
                        p.NomeReceptor.ToLower().Contains(search.ToLower()) ||
                        p.NifReceptor.ToLower().Contains(search.ToLower()) ||
                        p.NumDoc.ToString().ToLower().Contains(search.ToLower()) ||
                        p.Quantia.ToString().ToLower().Contains(search.ToLower()) ||
                        p.DataCriacao.ToString().ToLower().Contains(search.ToLower()) ||
                        p.TipoDoc.ToString().ToLower().Contains(search.ToLower()) ||
                        p.Estado.ToString().ToLower().Contains(search.ToLower())).ToList();
                }
                // Sorting.   
                data = this.SortByColumnWithOrder(order, orderDir, data, searchParam);
                // Filter record count.   
                int recFilter = data.Count;
                // Apply pagination.   
                data = data.Skip(startRec).Take(pageSize).ToList();
                // Loading drop down lists.   
                result = this.Json(new
                {
                    draw = Convert.ToInt32(draw),
                    recordsTotal = totalRecords,
                    recordsFiltered = recFilter,
                    data = data
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Info   
                Console.Write(ex);
            }
            // Return info.   
            return result;

        }

        

        public ActionResult Details(int? id, string direction)
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);

            if (!id.HasValue)
                RedirectToAction("Index");

            string label = direction == "Out" ? "Outbound" : "Inbound";
            label += " " + id.ToString();

            try
            {
                var packetInfo = _outboundInboundRepository.GetPacketById(id.Value, direction);

                PacketDetailVM k = (PacketDetailVM)packetInfo;

                //if (Request.IsAjaxRequest())
                //    return Json(this.PanelContentReply(packetInfo), JsonRequestBehavior.AllowGet);
                //else
                //return View(k);

                if (Request.IsAjaxRequest())
                    return Json(this.ModalContentReply(k), JsonRequestBehavior.AllowGet);
                else
                    return PartialView(k);

            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                return RedirectToAction("Index");
            }
        }

        public ActionResult FaturasOutros(JQueryDataTableParamModel param)
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);

            if (!Request.IsAjaxRequest())
            {
                return View("FaturasOutros");
            }
            var data = _eCConfigRepositories.ComATPacketRepository.GetComATPackets(_context.UserIdentity.Instances).ToList();

            var r = data.Select(o => new
            {
                NifRecetor = o.NIFReceptor,
                NDocumento = o.NumeroDocumento,
                DataDocumento = o.DataDocumento.ToShortDateString(),
                TotalIVA = o.TotalComIva,
                Estado = o.EstadoAT,

eBillingSuite/sourcecode/eBillingSuite.Host/Views/Stats/DocTransporte.cshtml
@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_LayoutStats.cshtml";
}
<script>
    function InitTable() {
        $('#jq-datatables').dataTable({
            "ajax": {
                "url": '@Url.Action("DocTransporte", "Stats")'
            },
            "order": [[0, "asc"]],
            "columnDefs": [
							{
							    "targets": 0,
							    "data": "NDocumento",
							},
							{
							    "targets": 1,
							    "data": "CodRetorno",
							},
							{
							    "targets": 2,
							    "data": "Estado",
							},
                            {
                                "targets": 3,
                                "data": "MsgRetornoAT",
                            },
                            {
                                "targets": 4,
                                "data": "UltimoEnvio",
                            },
            ],
            "language": {
                "sUrl": '@this.GetjQDataTableLanguageUrl()'
            }
        });

        $('#jq-datatables_wrapper .table-caption').text('');
        $('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');

        $('#jq-datatables').on('draw.dt', function () {

            $('#jq-datatables form').submit(function (e) {
                e.preventDefault();
                $.post($(this).prop('action'), $(this).serialize())
                    .success(function (data) {
                        if (data == "ok") {
                            var table = $('#jq-datatables').DataTable();
                            table.ajax.reload();
                        }
                    });
            });
        });


        var table = $('#jq-datatables').DataTable();

        $.fn.dataTableExt.afnFiltering.push(
            function filtragem(oSettings, aData, iDataIndex) {
                var iFini = $('#start').val();
                var iFfin = $('#end').val();
                if (iFini === "" && iFfin === "") {
                    return true;
                }
                var column = 4;

                var valoriFini = trocarValor(iFini.substring(3, 6));
                var valoriFfin = trocarValor(iFfin.substring(3, 6));

                iFini = iFini.substring(7, 9) + valoriFini + iFini.substring(0, 2);
                iFfin = iFfin.substring(7, 9) + valoriFfin + iFfin.substring(0, 2);

                var val = trocarValor(aData[column].substring(3, 6));

                var datofini = aData[column].substring(7, 9) + val + aData[column].substring(0, 2);

                if (iFini <= datofini && iFfin === "") {
                    return true;
                }
                else if (iFfin >= datofini && iFini === "") {
                    return true;
                }
                else if (iFini <= datofini && iFfin >= datofini) {
                    return true;
                }
                return false;
            }
        );

        function trocarValor(val) {
            if (val == "Jan")
                return "01";
            else if (val == "Feb")
                return "02";
            else if (val == "Mar")
                return "03";
            else if (val == "Apr")
                return "04";
            else if (val == "May")
                return "05";
            else if (val == "Jun")
                return "06";
            else if (val == "Jul")
                return "07";
            else if (val == "Aug")
                return "08";
            else if (val == "Sep")
                return "09";
            else if (val == "Oct")
                return "10";
            else if (val == "Nov")
                return "11";
            else if (val == "Dec")
                return "12";
        }
        function parseDateValue(rawDate) {
            var dateArray = rawDate.split("-");
            var parsedDate = dateArray[2] + dateArray[0] + dateArray[1];
            return parsedDate;
        }

        $('#jq-datatables tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });

        $('#ok').on('click', function () {
            //function filtragem() { table.draw(); };
            table.column(2).search($("#Estados").val()).draw();
            table.column(0).search($("#NumDoc").val()).draw();
        });


        $('#ok').on('click', function () {
            $('.dataTables_filter input').text($('#datepicker').val());
        });
        function exportToCsv() {
            var value = $('input[aria-controls=jq-datatables]').val();
            var params = "filter=" + value;
            document.location = '@Url.Action("ToCsv")?' + params;
        }

        function exportToPdf() {
            var value = $('input[aria-controls=jq-datatables]').val();
            var params = "filter=" + value;
            document.location = '@Url.Action("ToPdf")?' + params;
        }
    }
    init.push(function () {
        $('a[data-toggle=tooltip]').tooltip();

        InitTable();

        ajaxInitPanelFunctions['init-jqtable'] = InitTable;

        var options = {
            orientation: $('body').hasClass('right-to-left') ? "auto right" : 'auto auto',
            format: 'dd-M-yy'
        }
        $('#bs-datepicker-range').datepicker(options);

    });
</script>

<div class="panel panel-transparent">
    <div data-rel="ajax-update-panel" data-update-init="init-jqtable" data-modal-size="modal-lg">
        <div class="panel-heading">
            <span class="panel-title">@Texts.DocumentoTransporte</span>
            <br />
        </div>
        <div class="panel-body">
            <div class="row">                
                <div class="col-sm-6 col-sm-offset-6">
                    <div style="float:right;">
                        <button class="btn btn-app btn-grey btn-xxs radius-4" onclick="exportToPdf();">
                            <i class="fa  fa-file-text-o bigger-110"></i><br />
                            PDF
                        </button>

                        <button class="btn btn-app btn-grey btn-xxs radius-4" onclick="exportToCsv();">
                            <i class="fa fa-save bigger-110"></i><br />
                            CSV
                        </button>
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="Data"><small class="text-success">@Texts.Data</small></label>
                    <div class="input-daterange input-group" id="bs-datepicker-range">
                        <input class="input-sm form-control" id="start" name="start" placeholder="Start date" type="text">
                        <span class="input-group-addon">to</span>
                        <input class="input-sm form-control" id="end" name="end" placeholder="End date" type="text">
                    </div>
                </div>
                <div class="col-md-3">
                    <label for="Estado"><small class="text-success">@Texts.Estado</small></label>
                    <select class="form-control" id="Estados">
                        <option value="">&nbsp;</option>
                        <option value="0">0 - À espera de comunicação</option>
                        <option value="1">1 - Comunicado com sucesso</option>
                        <option value="2">2 - Erro na comunicação</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label><small class="text-success">@Texts.NumDocumento</small></label>
                    <input class="form-control" id="NumDoc" placeholder="NumDoc" type="text">
                </div>
                <label><small>&nbsp;</small></label><br />
                <button class="btn btn-primary btn" id="ok">OK</button>
            </div>
            <br />
            <div class="table-primary">
                <table cellpadding="0" width="100%" style="cursor:pointer" cellspacing="0" border="0" class="table table-striped table-hover table-bordered " id="jq-datatables" data-rel="ajax-update-panel" data-modal-size="modal-lg">
                    <thead>
                        <tr>
                            <th>Nº Documento</th>
                            <th>Código Retorno AT</th>
                            <th>Estado</th>
                            <th>Mensagem Retorno AT</th>
                            <th>Último Envio</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/Stats/DocumentosErros.cshtml
@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_LayoutStats.cshtml";
}

<script>
    function InitTable() {
        $('#jq-datatables').dataTable({
            "ajax": {
                "url": '@Url.Action("DocumentosErros", "Stats")'
            },
            "order": [[0, "asc"]],
            "columnDefs": [
							{
							    "targets": 0,
							    "data": "NumDoc",
							},
							{
							    "targets": 1,
							    "data": "NifEmissor",
							},
							{
							    "targets": 2,
							    "data": "NifRecetor",
							},
                            {
                                "targets": 3,
                                "data": "DataCriacao",

                            },
                            {
                                "targets": 4,
                                "data": "TipoErro",
                            },
                            {
                                "targets": 5,
                                "data": "DetalheErro",
                            },
                            {
                                "targets": 6,
                                "data": "Ficheiro"
                            },
            ],
            "language": {
                "sUrl": '@this.GetjQDataTableLanguageUrl()'
            }
        });

        $('#jq-datatables_wrapper .table-caption').text('');
        $('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');

        $('#jq-datatables').on('draw.dt', function () {

            $('#jq-datatables form').submit(function (e) {
                e.preventDefault();
                $.post($(this).prop('action'), $(this).serialize())
                    .success(function (data) {
                        if (data == "ok") {
                            var table = $('#jq-datatables').DataTable();
                            table.ajax.reload();
                        }
                    });
            });
        });


        var table = $('#jq-datatables').DataTable();

        $('#jq-datatables tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });



        $('#ok').on('click', function () {
            $('.dataTables_filter input').text($('#datepicker').val());
        });
    }
    @*function exportToCsv() {
        var value = $('input[aria-controls=sample-table-2]').val();
        var params = "filter=" + value;
        document.location = '@Url.Action("ToCsv")?' + params;
    }

    function exportToPdf() {
        var value = $('input[aria-controls=sample-table-2]').val();
        var params = "filter=" + value;
        document.location = '@Url.Action("ToPdf")?' + params;
    }*@
    init.push(function () {
        $('a[data-toggle=tooltip]').tooltip();

        InitTable();

        ajaxInitPanelFunctions['init-jqtable'] = InitTable;

        $('#bs-datepicker-component').datepicker();

    });
</script>

<div class="panel-heading">
    <span class="panel-title"> @this.Get(DictionaryEntryKeys.DocumentosErros) </span>
    <br />
</div>
<div class="panel-body">
    <div class="table-primary">
        <table cellpadding="0" width="100%" style="cursor:pointer" cellspacing="0" border="0" class="table table-striped table-hover table-bordered " id="jq-datatables" data-rel="ajax-update-panel" data-modal-size="modal-lg">
            <thead>
                <tr>
                    <th>Nº Documento</th>
                    <th>NIF Emissor</th>
                    <th>NIF Recetor</th>
                    <th>Data Criação</th>
                    <th>Tipo Erro</th>
                    <th>Detalhe Erro</th>
                    <th>Ficheiro</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/Stats/IntegratedFiles.cshtml
@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_LayoutStats.cshtml";
}

<script>
    function InitTable() {
        $('#jq-datatables').dataTable({
            "ajax": {
                "url": '@Url.Action("IntegratedFiles", "Stats")'
            },
            "order": [[0, "asc"]],
            "columnDefs": [
							{
							    "targets": 0,
							    "data": "NumDoc",
							},
							{
							    "targets": 1,
							    "data": "SubmissionF",
							},
                            {
							    "targets": 2,
							    "data": "SubmissionD",
							}
            ],
            "language": {
                "sUrl": '@this.GetjQDataTableLanguageUrl()'
            }
        });

        $('#jq-datatables_wrapper .table-caption').text('');
        $('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');

        $('#jq-datatables').on('draw.dt', function () {

            $('#jq-datatables form').submit(function (e) {
                e.preventDefault();
                $.post($(this).prop('action'), $(this).serialize())
                    .success(function (data) {
                        if (data == "ok") {
                            var table = $('#jq-datatables').DataTable();
                            table.ajax.reload();
                        }
                    });
            });
        });


        var table = $('#jq-datatables').DataTable();

        $('#jq-datatables tbody').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });



        $('#ok').on('click', function () {
            $('.dataTables_filter input').text($('#datepicker').val());
        });
    }
    function exportToCsv() {
        var value = $('input[aria-controls=jq-datatables]').val();
        var params = "filter=" + value;
        document.location = '@Url.Action("ToCsv")?' + params;
    }

    function exportToPdf() {
        var value = $('input[aria-controls=jq-datatables]').val();
        var params = "filter=" + value;
        document.location = '@Url.Action("ToPdf")?' + params;
    }
    init.push(function () {
        $('a[data-toggle=tooltip]').tooltip();

        InitTable();

        ajaxInitPanelFunctions['init-jqtable'] = InitTable;
        

    });
</script>

<div class="panel-heading">
    <span class="panel-title"> @Texts.IntegratedPackets</span>
    <br />
</div>
<div class="panel-body">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-6">
            <div style="float:right;">
                <button class="btn btn-app btn-grey btn-xxs radius-4" onclick="exportToPdf();">
                    <i class="fa  fa-file-text-o bigger-110"></i><br />
                    PDF
                </button>

                <button class="btn btn-app btn-grey btn-xxs radius-4" onclick="exportToCsv();">
                    <i class="fa fa-save bigger-110"></i><br />
                    CSV
                </button>
            </div>
        </div>
        <p>&nbsp;</p>
    </div>
    <div class="row">
        <div class="table-primary">
            <table cellpadding="0" width="100%" style="cursor:pointer" cellspacing="0" border="0" class="table table-striped table-hover table-bordered " id="jq-datatables" data-rel="ajax-update-panel" data-modal-size="modal-lg">
                <thead>
                    <tr>
                        <th>Número do Documento</th>
                        <th>Submission File</th>
                        <th>Submission Date</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>