eBillingSuite/sourcecode/eBillingSuite.Host/Controllers/eConnectorCustomersController.cs
using eBillingSuite.Globalization;
using eBillingSuite.Model.EBC_DB;
using eBillingSuite.Models;
using eBillingSuite.Repositories;
using eBillingSuite.Security;
using eBillingSuite.ViewModels;
using MvcFlash.Core;
using MvcFlash.Core.Extensions;
using Shortcut.PixelAdmin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBillingSuite.Controllers
{
    public class eConnectorCustomersController : Controller
    {
		private IPixelAdminPageContext _pixelAdminPageContext;
		protected readonly IeBillingSuiteRequestContext _context;		
		private IECCListRepositories _eCConfigRepositories;

		public eConnectorCustomersController(IPixelAdminPageContext pixelAdminPageContext,
			IECCListRepositories eCConfigRepositories,			
			IeBillingSuiteRequestContext context)
		{
			_pixelAdminPageContext = pixelAdminPageContext;			
			_eCConfigRepositories = eCConfigRepositories;
			_context = context;			
		}

		

		#region XmlConfigs
		[PersonAuthorize(Permissions.ECONNECTOR_CLIENTES_CONFIGURACOESXML)]
		public ActionResult XmlConfigs(Guid? id, Guid? idcustomer, string tipoxml)
		{		

			this.SetPixelAdminPageContext(_pixelAdminPageContext);

			if (!id.HasValue)
				id = _eCConfigRepositories.instancesRepository.GetEBC_Instances().FirstOrDefault().PKID;

			if (!idcustomer.HasValue)
				idcustomer = _eCConfigRepositories.eConnectorCustomersRepository
				.Where(ec => ec.FKInstanceID == id.Value).FirstOrDefault().PKID;

			var existingInstances = _eCConfigRepositories.instancesRepository.GetEBC_Instances();
			var modelVM = new EBCCustomersXMLConfigsVM(existingInstances, _eCConfigRepositories, id.Value, idcustomer.Value, tipoxml);

			if (Request.IsAjaxRequest())
				return Json(this.PanelContentReply(modelVM), JsonRequestBehavior.AllowGet);
			else
				return View(modelVM);
		}

		[PersonAuthorize(Permissions.ECONNECTOR_CLIENTES_CONFIGURACOESXML)]
		public ActionResult CreateXmlConfig(Guid id, Guid idcustomer, string tipoxml)
		{
			var numeroxml = _eCConfigRepositories.eConnectorXmlClientRepository.GetXMLClientNumberByFKClient(idcustomer);
			var modelVM = new EBCCustomersXMLConfigsVM(_eCConfigRepositories, id, idcustomer, tipoxml,numeroxml);

			if (Request.IsAjaxRequest())
				return Json(this.ModalContentReply("AddXmlConfig", modelVM), JsonRequestBehavior.AllowGet);
			else
				return PartialView("AddXmlConfig",modelVM);
		}

		[HttpPost]
		[PersonAuthorize(Permissions.ECONNECTOR_CLIENTES_CONFIGURACOESXML)]
		public ActionResult AddXmlConfig(Guid FKInstanceID, Guid FKCustomerID, XmlConfigData data)
		{
			if (!ModelState.IsValid)
			{
				var numeroxml = _eCConfigRepositories.eConnectorXmlClientRepository.GetXMLClientNumberByFKClient(FKCustomerID);
				var modelVM = new EBCCustomersXMLConfigsVM(_eCConfigRepositories, FKInstanceID, FKCustomerID, data.tipoXml, data.numeroxml);

				if (Request.IsAjaxRequest())
					return Json(this.ModalContentReply(modelVM), JsonRequestBehavior.AllowGet);
				else
					return PartialView(modelVM);
			}
			
			using (var dbContextTransaction = _eCConfigRepositories.instancesRepository.Context.Database.BeginTransaction())
			{
				try
				{
					
					if(data.isEdit)
					{
						char[] delimitador = { '-' };
						var valuestemp = data.selectedField.Split(delimitador);
						var nomecampo = valuestemp[0].TrimEnd();
						var campoBD = valuestemp[0].Replace(" ", "");
												
						if (valuestemp[1].Trim().ToLower().Equals(eBillingSuite.Enumerations.DigitalDocumentAreas.HEADER))
						{
							var dataFromDB = _eCConfigRepositories
								.eConnectorXmlHeaderRepository
								.Where(exh => exh.NumeroXML == data.numeroxml && exh.NomeCampo == nomecampo)
								.FirstOrDefault();

							dataFromDB.Obrigatorio = data.mandatory;

							_eCConfigRepositories
								.eConnectorXmlHeaderRepository
								.Edit(dataFromDB)
								.Save();
							
						}
						else if (valuestemp[1].Trim().ToLower().Equals(eBillingSuite.Enumerations.DigitalDocumentAreas.LINES))
						{
							var dataFromDB = _eCConfigRepositories
								.eConnectorXmlLinesRepository
								.Where(exh => exh.NumeroXML == data.numeroxml && exh.NomeCampo == nomecampo)
								.FirstOrDefault();

							dataFromDB.Obrigatorio = data.mandatory;

							_eCConfigRepositories
								.eConnectorXmlLinesRepository
								.Edit(dataFromDB)
								.Save();
						}
						else
						{
							var dataFromDB = _eCConfigRepositories
								.eConnectorXmlResumoIvaRepository
								.Where(exh => exh.NumeroXML == data.numeroxml && exh.NomeCampo == nomecampo)
								.FirstOrDefault();

							dataFromDB.Obrigatorio = data.mandatory;

							_eCConfigRepositories
								.eConnectorXmlResumoIvaRepository
								.Edit(dataFromDB)
								.Save();
						}
					}
					else
					{
						var tipoxmlOriginal = String.Empty;
						//verifica se o tipo de xml escolhido era o que estava escolhido anteriormente
						var exists = _eCConfigRepositories
							.eConnectorXmlHeaderRepository
							.Set.Any(exh => exh.NumeroXML == data.numeroxml);
						if (!exists)
						{
							exists = _eCConfigRepositories
							.eConnectorXmlLinesRepository
							.Set.Any(exh => exh.NumeroXML == data.numeroxml);
							if (!exists)
							{
								exists = _eCConfigRepositories
									.eConnectorXmlResumoIvaRepository
									.Set.Any(exh => exh.NumeroXML == data.numeroxml);
								if (!exists)
									tipoxmlOriginal = data.tipoXml;
								else
									tipoxmlOriginal = _eCConfigRepositories
									.eConnectorXmlLinesRepository
									.Where(exh => exh.NumeroXML == data.numeroxml)
									.FirstOrDefault()
									.TipoXML;
							}
							else
								tipoxmlOriginal = _eCConfigRepositories
									.eConnectorXmlLinesRepository
									.Where(exh => exh.NumeroXML == data.numeroxml)
									.FirstOrDefault()
									.TipoXML;
						}
						else
						{
							tipoxmlOriginal = _eCConfigRepositories
							.eConnectorXmlHeaderRepository
							.Where(exh => exh.NumeroXML == data.numeroxml)
							.FirstOrDefault()
							.TipoXML;
						}

						if (data.tipoXml != tipoxmlOriginal)
						{
							//tipo xml foi mudado.
							//apagar o que existe desse tipo xml para esse cliente

							_eCConfigRepositories
								.eConnectorXmlHeaderRepository
								.Set
								.RemoveRange(_eCConfigRepositories
								.eConnectorXmlHeaderRepository
								.Where(exh => exh.NumeroXML == data.numeroxml)
								.ToList());

							_eCConfigRepositories
								.eConnectorXmlLinesRepository
								.Set
								.RemoveRange(_eCConfigRepositories
								.eConnectorXmlLinesRepository
								.Where(exh => exh.NumeroXML == data.numeroxml)
								.ToList());

							_eCConfigRepositories
								.eConnectorXmlResumoIvaRepository
								.Set
								.RemoveRange(_eCConfigRepositories
								.eConnectorXmlResumoIvaRepository
								.Where(exh => exh.NumeroXML == data.numeroxml)
								.ToList());

						}

						//verificar se o campo e cabecalho, lineitem ou resumoiva
						char[] delimitador = { '-' };
						var valuestemp = data.selectedField.Split(delimitador);
						var nomecampo = valuestemp[0].TrimEnd();
						var campoBD = valuestemp[0].Replace(" ", "");

						if (valuestemp[1].Trim().ToLower().Equals(eBillingSuite.Enumerations.DigitalDocumentAreas.HEADER))
						{
							var dataForDB = new EBC_XML
							{
								NumeroXML = data.numeroxml,
								Element = _eCConfigRepositories
											.eConnectorXmlTemplateRepository.Where(ext => ext.TipoXML == data.tipoXml
												&&
												ext.Tipo.ToLower() == eBillingSuite.Enumerations.DigitalDocumentAreas.HEADER
												&&
												ext.NomeCampo == nomecampo
												)
												.FirstOrDefault()
												.CaminhoXML,
								NomeCampo = nomecampo,
								TipoXML = data.tipoXml,
								Obrigatorio = data.mandatory,
								Posicao = (_eCConfigRepositories
											.eConnectorXmlHeaderRepository
											.Where(exh => exh.NumeroXML == data.numeroxml)
											.OrderByDescending(exh => exh.Posicao).FirstOrDefault()
											.Posicao)
											+ 1,
								CampoBD = campoBD,
								isATfield = _eCConfigRepositories
												.eConnectorXmlTemplateRepository
												.Where(ext => ext.TipoXML == data.tipoXml
												&&
												ext.Tipo.ToLower() == eBillingSuite.Enumerations.DigitalDocumentAreas.HEADER
												&&
												ext.NomeCampo == nomecampo
												)
												.FirstOrDefault()
												.isATfield
							};

							_eCConfigRepositories
								.eConnectorXmlHeaderRepository
								.Add(dataForDB)
								.Save();
						}
						else if (valuestemp[1].Trim().ToLower().Equals(eBillingSuite.Enumerations.DigitalDocumentAreas.LINES))
						{
							var dataForDB = new EBC_XMLLines
							{
								NumeroXML = data.numeroxml,
								Element = _eCConfigRepositories
											.eConnectorXmlTemplateRepository.Where(ext => ext.TipoXML == data.tipoXml
												&&
												ext.Tipo.ToLower() == eBillingSuite.Enumerations.DigitalDocumentAreas.LINES
												&&
												ext.NomeCampo == nomecampo
												)
												.FirstOrDefault()
												.CaminhoXML,
								NomeCampo = nomecampo,
								TipoXML = data.tipoXml,
								Obrigatorio = data.mandatory,
								Posicao = (_eCConfigRepositories
											.eConnectorXmlLinesRepository
											.Where(exh => exh.NumeroXML == data.numeroxml)
											.OrderByDescending(exh => exh.Posicao)
											.FirstOrDefault()
											.Posicao)
											+ 1,
								CampoBD = campoBD,
								isATfield = _eCConfigRepositories
												.eConnectorXmlTemplateRepository
												.Where(ext => ext.TipoXML == data.tipoXml
												&&
												ext.Tipo.ToLower() == eBillingSuite.Enumerations.DigitalDocumentAreas.LINES
												&&
												ext.NomeCampo == nomecampo
												)
												.FirstOrDefault()
												.isATfield
							};

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eConnectorCustomers/AddXmlConfig.cshtml
@model eBillingSuite.ViewModels.EBCCustomersXMLConfigsVM
@{
	var uniqueID = "econnectorcustomerXMLConfig-modal";
}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 class="modal-title">@this.Get(DictionaryEntryKeys.EConnectorCustomerXMLConfigAdd)</h4>
</div>
<div class="modal-body">
	<form id="doc-edit-form"
		  action="@Url.Action("AddXmlConfig", "eConnectorCustomers")"
		  method="post"
		  class="form-horizontal">
		<div class="tab-content">
			<div id="@uniqueID-details" class="tab-pane fade in active">
				@Html.HiddenFor(e => e.FKCustomerID)
				@Html.HiddenFor(e => e.FKInstanceID)
				@Html.HiddenFor(e => e.numeroxml)
				@Html.HiddenFor(e => e.tipoXml)
				@Html.HiddenFor(e => e.isEdit)
				<div class="row">
					@Html.PixelAdminSelectWithColFor(e => e.selectedField, Model.AvailableFields, 6, null, Model.isEdit ? InputOptions.ReadOnly : InputOptions.Default)
					@Html.PixelAdminSwitcherWithColFor(e => Model.mandatory,6,null,InputOptions.Default)					
				</div>
			</div>
		</div>
	</form>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@this.Get(DictionaryEntryKeys.Submit)</button>
	<button type="button" class="btn btn-default" data-dismiss="modal">@this.Get(DictionaryEntryKeys.Close)</button>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eConnectorCustomers/CreateXmlField.cshtml
@model eBillingSuite.ViewModels.EBCXmlFieldSenderVM
@{
	var uniqueID = "edigitalheaderdoctypexml-modal";
}
<script type="text/javascript">
	$(document).ready(function () {
		$('#Area').change(function () {
			var selectedArea = $(this).val();
			if (selectedArea) {
				$('.page-alert').slideUp();
				if (selectedArea.toLowerCase() == 'cabecalho') {
					$('#headerFields, #requiredField').show();
					$('#linesFields, #vatFields').hide();
				} else if (selectedArea.toLowerCase() == 'lineitem') {
					$('#linesFields, #requiredField').show();
					$('#headerFields, #vatFields').hide();
				} else if (selectedArea.toLowerCase() == 'resumoiva') {
					$('#vatFields, #requiredField').show();
					$('#headerFields, #linesFields').hide();
				} else {
					$('#headerFields, #linesFields, #vatFields, #requiredField').hide();
					$('#alertMessage').text('Área desconhecida.');
					$('.page-alert').slideDown();
				}
			} else {
				$('#headerFields, #linesFields, #vatFields, #requiredField').hide();
				$('#alertMessage').text('Tem de selecionar um área.');
				$('.page-alert').slideDown();
			}
		});

		//Close alert
		$('.page-alert .close').click(function (e) {
			e.preventDefault();
			$(this).closest('.page-alert').slideUp();
		});
	});
</script>

<div class="page-alerts-3">
	<div class="alert alert-danger page-alert" id="alert-3" style="display: none;">
		<button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
		<strong id="alertMessage"></strong>
	</div>
</div>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 class="modal-title">@this.Get(DictionaryEntryKeys.XMLConfigSenderAdd)</h4>
</div>
<div class="modal-body">
	<form id="doc-edit-form"
		  action="@Url.Action("CreateXmlFieldSubmit", "eConnectorSenders")"
		  method="post"
		  class="form-horizontal">
		<div class="tab-content">
			<div id="@uniqueID-details" class="tab-pane fade in active">
				@Html.HiddenFor(e => e.XmlNumber)
				@Html.HiddenFor(e => e.XmlType)
				<div class="row">
					@Html.PixelAdminSelectWithColFor(e => e.Area, Model.AvailableAreas, 6, null, InputOptions.Default)
				</div>
				<div id="headerFields" class="row" style="display:none;">
					@Html.PixelAdminSelectWithColFor(e => e.NomeCampo, Model.AvailableHeaders, 6, null, InputOptions.Default)
				</div>
				<div id="linesFields" class="row" style="display:none;">
					@Html.PixelAdminSelectWithColFor(e => e.NomeCampo, Model.AvailableLines, 6, null, InputOptions.Default)
				</div>
				<div id="vatFields" class="row" style="display:none;">
					@Html.PixelAdminSelectWithColFor(e => e.NomeCampo, Model.AvailableIva, 6, null, InputOptions.Default)
				</div>
				<div id="requiredField" class="row" style="display:none;">
					@Html.PixelAdminSwitcherWithColFor(e => e.IsRequired, 2, null, InputOptions.Default)
				</div>
			</div>
		</div>
	</form>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@this.Get(DictionaryEntryKeys.Submit)</button>
	<button type="button" class="btn btn-default" data-dismiss="modal">@this.Get(DictionaryEntryKeys.Close)</button>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eConnectorCustomers/XmlConfigs.cshtml
@model eBillingSuite.ViewModels.EBCCustomersXMLConfigsVM
@{
	var isAjax = Request.IsAjaxRequest();
	Layout = isAjax ? null : "~/Views/Shared/_eConnectorCustomersLayout.cshtml";
}
@if (!isAjax)
{
	<script>

	function InitTable() {
		$('#jq-datatables').dataTable({

			"language": {
				"url": '@this.GetjQDataTableLanguageUrl()'
			},
		});
		$('#jq-datatables_wrapper .table-caption').text('');
		$('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');
	}

	init.push(function () {
		$('#FKInstanceID').change(function () {
			window.location = '@Html.Raw(@Url.Action("XmlConfigs", "eConnectorCustomers", new { id = "Guid", idcustomer = "GuidCustomer", tipoxml="tipoxml" }))'.replace('Guid', $('#FKInstanceID').find(":selected").val())
																																  .replace('GuidCustomer', $('#FKCustomerID').find(":selected").val())
																																  .replace('tipoxml', $('#tipoXml').find(":selected").val());
		});

		$('#FKCustomerID').change(function () {
			window.location = '@Html.Raw(@Url.Action("XmlConfigs", "eConnectorCustomers", new { id = "Guid", idcustomer = "GuidCustomer", tipoxml = "tipoxml" }))'.replace('Guid', $('#FKInstanceID').find(":selected").val())
																																	.replace('GuidCustomer', $('#FKCustomerID').find(":selected").val())
																																	.replace('tipoxml', $('#tipoXml').find(":selected").val());
		});

		$('#tipoXml').change(function () {
			console.log($('#tipoXml').find(":selected").val());
			window.location = '@Html.Raw(Url.Action("XmlConfigs", "eConnectorCustomers", new { id = "Guid", idcustomer = "GuidCustomer", tipoxml = "tipoxmlvalue" }))'.replace('Guid', $('#FKInstanceID').find(":selected").val())
																																.replace('GuidCustomer', $('#FKCustomerID').find(":selected").val())
																																.replace('tipoxmlvalue', $('#tipoXml').find(":selected").val());
		});

		$('a[data-toggle=tooltip]').tooltip();
		InitTable();
		ajaxInitPanelFunctions['init-jqtable'] = InitTable;

	});
</script>
}
<div class="tab-pane panel no-padding no-border fade in active"
	 data-rel="ajax-update-panel"
	 id="IndexConnectorConfigTXT"
	 data-update-init="init-jqtable"
	 data-update-url="@Url.Action("XmlConfigs")"
	 data-create-url="@Url.Action("CreateXmlConfig", "eConnectorCustomers", new { id = Model.FKInstanceID, idcustomer = Model.FKCustomerID, tipoxml = Model.tipoXml })"
	 data-modal-size="modal-lg">
	<div class="panel-heading">
		<span class="panel-title">@this.Get(DictionaryEntryKeys.eConnectorCustomersTitle)</span>
	</div>
	<div class="panel-body">
		<div class="row">
			@Html.PixelAdminSelectWithColFor(e => e.FKInstanceID, Model.AvailableInstances, 4, null, InputOptions.Default)		
			@if(Model.FKCustomerID != null)
			{
				@Html.PixelAdminSelectWithColFor(e => e.FKCustomerID, Model.AvailableCustomers, 4, null, InputOptions.Default)			
			}	
			
			@Html.PixelAdminSelectWithColFor(e => e.tipoXml, Model.AvailableTypes, 4, null, InputOptions.Default)
		</div>
	</div>

	<div class="panel-heading">
		<span class="panel-title">@this.Get(DictionaryEntryKeys.CustomersList)</span>
		<div class="panel-heading-controls">
			<button type="button"
					data-rel="ajax-create-trigger"
					title="@this.Get(DictionaryEntryKeys.CustomerAdd)"
					class="btn btn-xs btn-primary">
				<i class="fa fa-plus"></i>
			</button>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-primary">
			<table cellpadding="0"
				   cellspacing="0"
				   border="0"
				   class="table table-striped table-bordered"
				   id="jq-datatables">
				<thead>
					<tr>
						<th>@this.Get(DictionaryEntryKeys.NomeCampo)</th>
						<th class="visible-lg">@this.Get(DictionaryEntryKeys.Tipo)</th>
						<th>@this.Get(DictionaryEntryKeys.Obrigatorio)</th>
						<th class="visible-lg">@this.Get(DictionaryEntryKeys.Posicao)</th>
						<th>@this.Get(DictionaryEntryKeys.CampoAT)</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@if (Model.FKCustomerID != null)
					{
						foreach (eBillingSuite.Model.EBC_DB.EBC_XML cap in Model.xmlheaders)
						{
							<tr>
								<td>@cap.NomeCampo</td>
								<td class="visible-lg">@this.Get(DictionaryEntryKeys.Cabecalho)</td>
								@if (cap.Obrigatorio.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td class="visible-lg">@cap.Posicao</td>
								@if (cap.isATfield.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td style="text-align:right; white-space:nowrap">
									<button type="button" class="btn btn-primary btn-sm" data-rel="ajax-edit-trigger" data-url="@Url.Action("EditXmlConfig", "eConnectorCustomers", new { id=Model.FKInstanceID, idcustomer = Model.FKCustomerID, tipoxml= Model.tipoXml, numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-pencil"></i></button>
									<button type="button" class="btn btn-danger btn-sm" data-rel="ajax-delete-trigger" data-url="@Url.Action("DeleteXmlConfig", "eConnectorCustomers", new { numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-times"></i></button>
								</td>
							</tr>
						}
						foreach (eBillingSuite.Model.EBC_DB.EBC_XMLLines cap in Model.xmllines)
						{
							<tr>
								<td>@cap.NomeCampo</td>
								<td class="visible-lg">@this.Get(DictionaryEntryKeys.LineItem)</td>
								@if (cap.Obrigatorio.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td class="visible-lg">@cap.Posicao</td>
								@if (cap.isATfield.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td style="text-align:right; white-space:nowrap">
									<button type="button" class="btn btn-primary btn-sm" data-rel="ajax-edit-trigger" data-url="@Url.Action("EditXmlConfig", "eConnectorCustomers", new { id=Model.FKInstanceID, idcustomer = Model.FKCustomerID, tipoxml= Model.tipoXml, numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-pencil"></i></button>
									<button type="button" class="btn btn-danger btn-sm" data-rel="ajax-delete-trigger" data-url="@Url.Action("DeleteXmlConfig", "eConnectorCustomers", new { numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-times"></i></button>
								</td>
							</tr>
						}
						foreach (eBillingSuite.Model.EBC_DB.EBC_XMLResumoIVA cap in Model.xmliva)
						{
							<tr>
								<td>@cap.NomeCampo</td>
								<td class="visible-lg">@this.Get(DictionaryEntryKeys.LineItem)</td>
								@if (cap.Obrigatorio.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td class="visible-lg">@cap.Posicao</td>
								@if (cap.isATfield.Value)
								{
									<td><span class="label label-success label-tag">@this.Get(DictionaryEntryKeys.Sim)</span></td>
								}
								else
								{
									<td><span class="label label-primary label-tag">@this.Get(DictionaryEntryKeys.Nao)</span></td>
								}
								<td style="text-align:right; white-space:nowrap">
									<button type="button" class="btn btn-primary btn-sm" data-rel="ajax-edit-trigger" data-url="@Url.Action("EditXmlConfig", "eConnectorCustomers", new { id=Model.FKInstanceID, idcustomer = Model.FKCustomerID, tipoxml= Model.tipoXml, numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-pencil"></i></button>
									<button type="button" class="btn btn-danger btn-sm" data-rel="ajax-delete-trigger" data-url="@Url.Action("DeleteXmlConfig", "eConnectorCustomers", new { numeroxml = cap.NumeroXML, nomecampo = cap.NomeCampo })"><i class="fa fa-times"></i></button>
								</td>
							</tr>
						}
					}
					
				</tbody>
			</table>
		</div>
	</div>
</div>