eBillingSuite/sourcecode/eBillingSuite.Host/Controllers/eDigitalController.cs
using eBillingSuite.Security;
using eBillingSuite.ViewModels;
using System.Web.Mvc;

using eBillingSuite.Globalization;
using eBillingSuite.Models;
using eBillingSuite.Repositories;
using MvcFlash.Core;
using MvcFlash.Core.Extensions;
using Shortcut.PixelAdmin;
using System;
using System.Collections.Generic;
using System.Linq;
using eBillingSuite.Integrations;
using System.IO;
using eBillingSuite.Enumerations;
using eBillingSuite.HelperTools;
using eBillingSuite.Support;
using System.Data;
using eBillingSuite.Model.Desmaterializacao;
using eBillingSuite.Model.eBillingConfigurations;
using System.Web.Script.Serialization;
using eBillingSuite.Repositories.Interfaces.eDigital;
using eBillingSuite.Resources;

namespace eBillingSuite.Controllers
{
    public class eDigitalController : Controller
    {
        private IPixelAdminPageContext _pixelAdminPageContext;
        private IeBillingSuiteRequestContext _context;
        private IEDigitalSuppliersRepository _eDigitalSuppliersRepository;
        private ISupplierSyncronization _supplierSyncronization;
        private IEDigitalDocTypeRepository _eDigitalDocTypeRepository;
        private IEDigitalDocTypeXmlDataRepository _eDigitalDocTypeXmlDataRepository;
        private IEDigitalTemplateNameRepository _eDigitalTemplateNameRepository;
        private IEDigitalSupplierXmlDataRepository _eDigitalSupplierXmlDataRepository;
        private IEDigitalDocExpirationRepository _eDigitalDocExpirationRepository;
        private IEDigitalDocHistoryRepository _eDigitalDocHistoryRepository;
        private IEDigitalXmlFieldsRepository _eDigitalXmlFieldsRepository;
        private IEDigitalMasterizationHeaderRepository _eDigitalMasterizationHeaderRepository;
        private IEDigitalMasterizationLinesRepository _eDigitalMasterizationLinesRepository;
        private IEDigitalMasterizationVatRepository _eDigitalMasterizationVatRepository;
        private IEDigitalIntancesRepository _eDigitalInstancesRepository;
        private IEDigitalMasterizationProcRepository _eDigitalMasterizationProcRepository;
        private IDigitalConfigurationsRepository _eDigitalConfigurationsRepository;
        private IAccountingData _accountingData;
        private IEDigitalInstancesMailRepository _eDigitalInstancesMailRepository;

        public eDigitalController(IPixelAdminPageContext pixelAdminPageContext,
            IeBillingSuiteRequestContext context,
            IEDigitalSuppliersRepository eDigitalSuppliersRepository,
            ISupplierSyncronization supplierSyncronization,
            IEDigitalDocTypeRepository eDigitalDocTypeRepository,
            IEDigitalDocTypeXmlDataRepository eDigitalDocTypeXmlDataRepository,
            IEDigitalTemplateNameRepository eDigitalTemplateNameRepository,
            IEDigitalSupplierXmlDataRepository eDigitalSupplierXmlDataRepository,
            IEDigitalDocExpirationRepository eDigitalDocExpirationRepository,
            IEDigitalDocHistoryRepository eDigitalDocHistoryRepository,
            IEDigitalXmlFieldsRepository eDigitalXmlFieldsRepository,
            IEDigitalMasterizationHeaderRepository eDigitalMasterizationHeaderRepository,
            IEDigitalMasterizationLinesRepository eDigitalMasterizationLinesRepository,
            IEDigitalIntancesRepository eDigitalInstancesRepository,
            IEDigitalMasterizationProcRepository eDigitalMasterizationProcRepository,
            IEDigitalMasterizationVatRepository eDigitalMasterizationVatRepository,
            IDigitalConfigurationsRepository eDigitalConfigurationsRepository,
            IAccountingData accountingData,

            IEDigitalInstancesMailRepository eDigitalInstancesMailRepository)
        {
            _pixelAdminPageContext = pixelAdminPageContext;
            _context = context;
            _eDigitalSuppliersRepository = eDigitalSuppliersRepository;
            _eDigitalConfigurationsRepository = eDigitalConfigurationsRepository;
            _supplierSyncronization = supplierSyncronization;
            _eDigitalDocTypeRepository = eDigitalDocTypeRepository;
            _eDigitalDocTypeXmlDataRepository = eDigitalDocTypeXmlDataRepository;
            _eDigitalTemplateNameRepository = eDigitalTemplateNameRepository;
            _eDigitalSupplierXmlDataRepository = eDigitalSupplierXmlDataRepository;
            _eDigitalDocExpirationRepository = eDigitalDocExpirationRepository;
            _eDigitalDocHistoryRepository = eDigitalDocHistoryRepository;
            _eDigitalXmlFieldsRepository = eDigitalXmlFieldsRepository;
            _eDigitalMasterizationHeaderRepository = eDigitalMasterizationHeaderRepository;
            _eDigitalMasterizationLinesRepository = eDigitalMasterizationLinesRepository;
            _eDigitalMasterizationVatRepository = eDigitalMasterizationVatRepository;
            _eDigitalInstancesRepository = eDigitalInstancesRepository;
            _eDigitalMasterizationProcRepository = eDigitalMasterizationProcRepository;
            _accountingData = accountingData;
            _eDigitalInstancesMailRepository = eDigitalInstancesMailRepository;
        }

        #region Fornecedores
        //[PersonAuthorize(Permissions.EDIGITAL_FORNECEDORES)]
        //public ActionResult Index()
        //{
        //	this.SetPixelAdminPageContext(_pixelAdminPageContext);

        //	if (!_context.UserIdentity.IsEBDActive)
        //		return View("InactiveModule");

        //	var model = _eDigitalSuppliersRepository
        //		.Set
        //		.OrderBy(x => x.Nome)
        //		.ToList();

        //	if (Request.IsAjaxRequest())
        //		return Json(this.PanelContentReply(model), JsonRequestBehavior.AllowGet);
        //	else
        //		return View(model);
        //}
        [PersonAuthorize(Permissions.EDIGITAL_FORNECEDORES)]
        public ActionResult Index(JQueryDataTableParamModel param)
        {
            this.SetPixelAdminPageContext(_pixelAdminPageContext);

            if (!_context.UserIdentity.IsEBDActive)
                return View("InactiveModule");

            if (!Request.IsAjaxRequest())
            {
                return View("Index");
            }

            var model = _eDigitalSuppliersRepository
                .Set
                .OrderBy(x => x.Nome)
                .ToList();

            //para a ordenação
            var isNomeSortable = Convert.ToBoolean(Request["bSortable_1"]);
            var isNIFSortable = Convert.ToBoolean(Request["bSortable_2"]);
            var isValidacoesSortable = Convert.ToBoolean(Request["bSortable_3"]);
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);

            Func<Fornecedores, string> orderingFunction = (c => sortColumnIndex == 0 && isNomeSortable ? c.Nome :
                sortColumnIndex == 1 && isNIFSortable ? c.Contribuinte.ToString() :
                sortColumnIndex == 2 && isValidacoesSortable ? c.WantMainValidations.ToString() :
                                                           "");

            var orderedQuery = Request["sSortDir_0"] == "asc" ?
                model.OrderBy(orderingFunction) :
                model.OrderByDescending(orderingFunction);

            if (param.iDisplayLength != 0)
            {
                var recordCount = model.Count();
                var records = orderedQuery
                    .Skip(param.iDisplayStart)
                    .Take(param.iDisplayLength)
                    .ToList();

                var reply = new JsonNetResult();
                reply.Data = new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = recordCount,
                    iTotalDisplayRecords = param.iDisplayLength,
                    aaData = records
                };

                return reply;
            }
            else
            {
                var records = orderedQuery.Take(10).ToList();
                var reply = new JsonNetResult();
                reply.Data = new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = model.Count(),
                    iTotalDisplayRecords = records.Count,
                    aaData = orderedQuery
                };

                return reply;
            }

            //if (Request.IsAjaxRequest())
            //	return Json(this.PanelContentReply(model), JsonRequestBehavior.AllowGet);
            //else
            //	return View(model);
        }

        [PersonAuthorize(Permissions.EDIGITAL_FORNECEDORES)]
        public ActionResult EditSupplier(Guid pkid)
        {
            var model = _eDigitalSuppliersRepository.Find(pkid);

            //ViewBag.SupplierSync = _eDigitalConfigurationsRepository.GetConfigurationByKey("SincFornecedoresWS") != null ?
            //    ((bool)_eDigitalConfigurationsRepository.GetConfigurationByKey("SincFornecedoresWS") ? "true" : "false") : "false";

            string wantSupplierSync = String.IsNullOrEmpty(_eDigitalConfigurationsRepository.GetConfigurationByKey("SincFornecedoresWS").ToString())
                                      ? "false" : "true";

            ViewBag.SupplierSync = wantSupplierSync;

            if (Request.IsAjaxRequest())
                return Json(this.ModalContentReply(model), JsonRequestBehavior.AllowGet);
            else
                return PartialView(model);
        }

        [HttpPost]
        //[PersonAuthorize(Permissions.EDIGITAL_FORNECEDORES)]
        public ActionResult EditSupplier(Guid pkid, DigitalSupplierData data, bool returnInsertedId = false)
        {
            var dataFromDB = _eDigitalSuppliersRepository.Find(pkid);

            if (!ModelState.IsValid)
            {
                Flash.Instance.Error(Texts.FixModelErrors);


                string wantSupplierSync = String.IsNullOrEmpty(_eDigitalConfigurationsRepository.GetConfigurationByKey("SincFornecedoresWS").ToString())
                                      ? "false" : "true";

                ViewBag.SupplierSync = wantSupplierSync;

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/CreateDocumentType.cshtml
@model eBillingSuite.ViewModels.EDigitalCreateDocTypeVM
@{
	var uniqueID = "edigitaldocumenttype-modal";

}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 class="modal-title">@Texts.DigitalDocumentTypeAdd</h4>
</div>
<div class="modal-body">
	<form id="doc-edit-form"
		  action="@Url.Action("CreateDocumentType", "eDigital")"
		  method="post"
		  class="form-horizontal">
		<div class="tab-content">
			<div id="@uniqueID-details" class="tab-pane fade in active">
				@Html.HiddenFor(e => e.TipoFactura.pkid)
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.TipoFactura.nome, 6, null, InputOptions.Default, Texts.TipoFatura)
					@Html.PixelAdminTextBoxWithColFor(e => e.NomeTemplate, 6, null, InputOptions.Default, Texts.NomeTemplate)
				</div>
				<div class="row">
						@Html.PixelAdminTextBoxWithColFor(e => e.TipoFactura.RecognitionTags, 12, null, InputOptions.Default, Texts.RecognitionTags)
				</div>
				<div class="row">
					@Html.PixelAdminSwitcherWithColFor(e => e.IsGenericDocument, 12, null, InputOptions.Default, Texts.isGenericDocument)
				</div>
				<p class="help-block">@Texts.DigitalDocTypeTagsHelpLine</p>
			</div>
		</div>
	</form>
</div>
<div class="modal-footer">
	<button id="submitBtt" type="button" class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@Texts.Submit</button>
	<button type="button" class="btn btn-default" data-dismiss="modal">@Texts.Close</button>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/CreateInstance.cshtml
@model eBillingSuite.Model.Desmaterializacao.Instances
@{
	var uniqueID = "edigitalinstance-modal";
}

<script>
	$(document).ready(function () {
		//Close alert
		$('.page-alert .close').click(function (e) {
			e.preventDefault();
			$(this).closest('.page-alert').slideUp();
		});
	});
</script>

<div class="page-alerts">
	<div class="alert alert-danger page-alert" id="alert-2" style="display: none;">
		<button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
		<strong>@Texts.DigitalAlertFillVat</strong>
	</div>
</div>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 class="modal-title">@Texts.DigitalInstanceAdd</h4>
</div>
<div class="modal-body">
	<form id="doc-edit-form"
		  action="@Url.Action("CreateDigitalInstance", "eDigital")"
		  method="post"
		  class="form-horizontal"
		  data-get-on-close="true">
		<div class="tab-content">
			<div id="@uniqueID-details" class="tab-pane fade in active">
				@*@Html.HiddenFor(e => e.pkid)*@
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Name, 6, null, InputOptions.Default, Texts.Name)
				</div>
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.VatNumber, 6, null, InputOptions.Default, Texts.NIF)
                    @Html.PixelAdminTextBoxWithColFor(e => e.InternalCode, 6, null, InputOptions.Default, Texts.InternalCode)
				</div>
			</div>
		</div>
	</form>
</div>
<div class="modal-footer">
	<button id="submitBtt" type="button" class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@Texts.Submit</button>
	<button type="button" class="btn btn-default" data-dismiss="modal">@Texts.Close</button>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/CreateSupplier.cshtml
@model eBillingSuite.Model.Desmaterializacao.Fornecedores
@{
    var uniqueID = "edigitalsupplier-modal";

    var wantSupplierSync = ViewBag.SupplierSync as string;
    //var wantSupplierSync = "true";

    var option = wantSupplierSync.ToLower() == "true" ? InputOptions.ReadOnly : InputOptions.Default;

    var bttDisabled = wantSupplierSync.ToLower() == "true" ? "disabled" : "";
}

<script>
	$(document).ready(function () {
		$('#searchSupplierBtt').click(function () {
			var nif = $("#Contribuinte").val();
			if (nif == "") {
				$('#alert-2').slideDown();
			} else {
				$.ajax({
					type: 'POST',
					url: '@Url.Action("GetSupplierData", "eDigital")',
					data: {
						'nif': nif
					},
					success: function (data) {
						if (data != null) {
							var mydata = data;
							success(mydata);
						}
					}
				});
			}
		});

		//Close alert
		$('.page-alert .close').click(function (e) {
			e.preventDefault();
			$(this).closest('.page-alert').slideUp();
		});
	});

	function success(mydata) {
		if (mydata.Nome != null && mydata.Nome != "") {
			$("#Nome").prop("readonly", true).val(mydata.Nome);
		} else {
			$("#Nome").prop("readonly", false);
		}

		if (mydata.Telefone != null && mydata.Telefone != "") {
			$("#Telefone").prop("readonly", true).val(mydata.Telefone);
		} else {
			$("#Telefone").prop("readonly", false);
		}

		if (mydata.Fax != null && mydata.Fax != "") {
			$("#Fax").prop("readonly", true).val(mydata.Fax);
		} else {
			$("#Fax").prop("readonly", false);
		}

		if (mydata.Morada != null && mydata.Morada != "") {
			$("#Morada").prop("readonly", true).val(mydata.Morada);
		} else {
			$("#Morada").prop("readonly", false);
		}

		if (mydata.Email != null && mydata.Email != "") {
			$("#Email").prop("readonly", true).val(mydata.Email);
		} else {
			$("#Email").prop("readonly", false);
		}

		if (mydata.WebSite != null && mydata.WebSite != "") {
			$("#WebSite").prop("readonly", true).val(mydata.WebSite);
		} else {
			$("#WebSite").prop("readonly", false);
		}

		$("#submitBtt").prop("disabled", false);
	}
</script>

<div class="page-alerts">
	<div class="alert alert-danger page-alert" id="alert-2" style="display: none;">
		<button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
		<strong>@Texts.DigitalAlertFillVat</strong>
	</div>
</div>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h4 class="modal-title">@Texts.DigitalSenderAdd</h4>
</div>
<div class="modal-body">
	<form id="doc-edit-form"
		  action="@Url.Action("CreateDigitalSupplier", "eDigital")"
		  method="post"
		  class="form-horizontal"
		  data-get-on-close="true">
		<div class="tab-content">
			<div id="@uniqueID-details" class="tab-pane fade in active">
				@Html.HiddenFor(e => e.pkid)
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Contribuinte, 6, null, InputOptions.Default, Texts.NIF)
					@if (wantSupplierSync.ToLower() == "true")
					{
						<div class="col-lg-6" style="padding-top:25px;">
							<div class="form-group no-margin-hr">
								<a id="searchSupplierBtt" class="btn btn-primary">@Texts.Procurar</a>
							</div>
						</div>
					}
				</div>
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Nome, 12, null, option, Texts.Name)
				</div>
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Morada, 12, null, option, Texts.Morada)
				</div>
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Telefone, 6, null, option, Texts.Telefone)
					@Html.PixelAdminTextBoxWithColFor(e => e.Fax, 6, null, option, Texts.Fax)
				</div>
				<div class="row">
					@Html.PixelAdminTextBoxWithColFor(e => e.Email, 6, null, option, Texts.EmailAddress)
					@Html.PixelAdminTextBoxWithColFor(e => e.WebSite, 6, null, option, Texts.Website)
				</div>
			</div>
		</div>
	</form>
</div>
<div class="modal-footer">
	<button id="submitBtt" type="button" @bttDisabled class="btn btn-primary" data-rel="submit" data-form="doc-edit-form">@Texts.Submit</button>
	<button type="button" class="btn btn-default" data-dismiss="modal">@Texts.Close</button>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/DigitalAccountingData.cshtml
@*@model eBillingSuite.ViewModels.EDigitalSupplierSyncVM*@
@{
    var isAjax = Request.IsAjaxRequest();
    Layout = isAjax ? null : "~/Views/Shared/_eDigitalLayout.cshtml";
}
<script type="text/javascript">
    init.push(function () {
        $('#FicheiroCSV').pixelFileInput();

        $("form").submit(function () {
            var val = $('#FicheiroCSV').val().toLowerCase();

            console.log('val = ' + val);

            var regex = new RegExp("(.*?)\.(csv)$");
            if (!(regex.test(val))) {
                $(this).val('');
                alert('Só são permitidos ficheiros CSV.');
                return false;
            }
        });
    });
</script>

<div class="tab-pane panel no-padding no-border fade in active">
    <form method="post" action="@Url.Action("UploadAccountingData", "eDigital")" enctype="multipart/form-data">
        <div class="panel-heading">
            <span class="panel-title">@Texts.DigitalUploadAccountingData</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group no-margin-hr">
                        <label for="FicheiroCSV" class="control-label">@Texts.CSVFile</label>
                        <input type="file" name="FicheiroCSV" id="FicheiroCSV" value="" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group no-margin-hr">
                        <p class="help-block">Formato do ficheiro CSV Contabilidade</p>
                        <p class="help-block">Entidade;NIFTerceiro;CodigoTerceiro;ContaTerceiro;TipoDoc;ContaBase;CodIVA;ContaIVA;ContaIVAintraC;ContaIS;ContaBaseRed;CodIVARed;ContaIVARed;ContaBaseInt;CodIVAInt;ContaIVAInt</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer text-right">
            <button class="btn btn-primary">@Texts.Upload</button>
        </div>
    </form>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/DigitalProc.cshtml
@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_eDigitalLayout.cshtml";

    var user = User.Identity as eBillingSuite.Security.IeBillingSuiteIdentity;
    var routeDataValues = Request.RequestContext.RouteData.Values;
    var action = routeDataValues["action"].ToString().ToLower();
}

<script>
    function InitTable() {
		$('#jq-datatables').dataTable({
			"ajax": {
				"url": '@Url.Action("DigitalProc","eDigital")',
			},
			"order": [[0, "asc"]],
			"columnDefs": [
							{
								"targets": 0,
								"data": "Prioridade",
							},
							{
								"targets": 1,
								"data": "nomeficheiro",
							},
							{
							    "targets": 2,
							    "data": "dtaCriacao",
							    "type": "html"
							},
                            {
                                "targets": 3,
                                "data": "DtaModificacao",
                            },
                            {
                                "targets": 4,
                                "data": "Utilizador",
                            }
			],
			"olanguage": {
				"sUrl": '@this.GetjQDataTableLanguageUrl()'
			},
		});

		$('#jq-datatables_wrapper .table-caption').text('');
		$('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');

		$('#jq-datatables').on('draw.dt', function () {

			$('#jq-datatables form').submit(function (e) {
				e.preventDefault();
				$.post($(this).prop('action'), $(this).serialize())
					.success(function (data) {
						if (data == "ok") {
							var table = $('#jq-datatables').DataTable();
							table.ajax.reload();
						}
					});
			});
		});
	}

	init.push(function () {
		$('a[data-toggle=tooltip]').tooltip();

		InitTable();

		ajaxInitPanelFunctions['init-jqtable'] = InitTable;
	});
</script>

<div class="tab-pane panel no-padding no-border fade in active">
    <div data-rel="ajax-update-panel"
         id="IndexEDICostumers"
         data-update-init="init-jqtable"
         data-modal-size="modal-lg">
        <div class="panel-heading">
            <span class="panel-title">@Texts.ProcDocs</span>
        </div>
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables" data-rel="ajax-update-panel" data-modal-size="modal-lg" width="100%">
                    <thead>
                        <tr>
                            
                            <th>@Texts.Prioridade</th>
                            <th>@Texts.NomeFicheiro</th>
                            <th>@Texts.DtaCriacao</th>
                            <th>@Texts.DtaModi</th>   
                            <th>@Texts.Username</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/DocumentsHistoric.cshtml
@model eBillingSuite.ViewModels.EDigitalDocumentHistoryVM
@{
	Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_eDigitalLayout.cshtml";
}
<script>
	init.push(function () {
		$('a[data-toggle=tooltip]').tooltip();
		$('#jq-datatables').dataTable({

			"language": {
				"url": '@this.GetjQDataTableLanguageUrl()'
					},
		});
		$('#jq-datatables_wrapper .table-caption').text('');
		$('#jq-datatables_wrapper .dataTables_filter input').attr('placeholder', 'Procurar');
	});
</script>

<div class="tab-pane panel no-padding no-border fade in active">
	<form method="post"
		  data-rel="ajax-update-panel"
		  id="IndexEDICostumers"
		  data-modal-size="modal-lg">
		<div class="panel-heading">
			<span class="panel-title">@Texts.DigitalDocHistoryTitle</span>
			@*<div class="panel-heading-controls">
				<button type="button"
						data-rel="ajax-create-trigger"
						data-method="post"
						title="@this.Get(DictionaryEntryKeys.DigitalSupplierAdd)"
						class="btn btn-xs btn-primary">
					<i class="fa fa-plus"></i>
				</button>
			</div>*@
		</div>
		<div class="panel-body">
			<div class="table-primary">
				<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables">
					<thead>
						<tr>
							<th>@Texts.DigitalDocNumber</th>
							<th>@Texts.DigitalDocSupplier</th>
							<th>@Texts.DigitalDocValidationDate</th>
							<th>@Texts.DigitalDocValidationUser</th>
							<th>@Texts.DigitalDocXml</th>
							<th>@Texts.DigitalDocPdf</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var forn in Model.documentDetails)
						{
							var xmlUrl = Url.Action("DownloadFile", "eDigital") + "?filename=" + @forn.XmlFilename;
							var pdfUrl = Url.Action("DownloadFile", "eDigital") + "?filename=" + @forn.PdfFilename;
							<tr>
								<td>@forn.DocNumber</td>
								<td>@forn.Fornecedor</td>
								<td>@forn.ValidationDate.ToString()</td>
								<td>@forn.ValidationUser</td>
								<td style="text-align:center;"><a href="@xmlUrl" target="_self"><i class="fa fa-cloud-download fa-2x"></i></a></td>
								<td style="text-align:center;"><a href="@pdfUrl" target="_self"><i class="fa fa-cloud-download fa-2x"></i></a></td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	</form>
</div>

eBillingSuite/sourcecode/eBillingSuite.Host/Views/eDigital/InactiveModule.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-transparent">
			<div class="panel-body">
				<div class="alert alert-info alert-dark">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong>Módulo inativo!</strong>&nbsp;Caro utilizador, este módulo encontra-se inativo. Para mais informações, sobre este e outros produtos, consulte o nosso <a href="http://www.pi-co.com/ebilling-digital" target="_blank"><strong>site</strong></a> .
				</div>
				<img class="img-responsive" src="~/assets/PI/Images/schema_digital.gif" alt="Arquitetura eBilling Suite" style="margin-left: auto; margin-right:auto;" />
			</div>
		</div>
	</div>
</div>